# inherit_from: .rubocop_todo.yml
require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
    Max: 120
Metrics/MethodLength:
    Max: 25

Style/Documentation:
  Enabled: false
